"""add change records

Revision ID: 0072ec287e7b
Revises: 8856cd2509f4
Create Date: 2026-08-04 12:11:46.309511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0072ec287e7b'
down_revision: Union[str, Sequence[str], None] = '8856cd2509f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_or_topic', sa.String(length=150), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('change_value', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=30), nullable=True),
    sa.Column('materiality_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('previous_period', sa.String(length=50), nullable=True),
    sa.Column('current_period', sa.String(length=50), nullable=True),
    sa.Column('first_known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_records')
    # ### end Alembic commands ###
