"""add nse listing fields

Revision ID: 0bb85d5f10e4
Revises: 3b70a1b988f7
Create Date: 2026-07-31 12:45:55.116242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb85d5f10e4'
down_revision: Union[str, Sequence[str], None] = '3b70a1b988f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('series', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('listing_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('market_lot', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'face_value')
    op.drop_column('companies', 'market_lot')
    op.drop_column('companies', 'listing_date')
    op.drop_column('companies', 'series')
    # ### end Alembic commands ###
