"""add change strength fields

Revision ID: 176e2ebb16b9
Revises: 49126c697e4d
Create Date: 2026-08-06 10:52:05.029219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176e2ebb16b9'
down_revision: Union[str, Sequence[str], None] = '49126c697e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_records', sa.Column('evidence_strength_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('specificity_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('css_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('css_model_version', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_records', 'css_model_version')
    op.drop_column('change_records', 'css_score')
    op.drop_column('change_records', 'specificity_score')
    op.drop_column('change_records', 'evidence_strength_score')
    # ### end Alembic commands ###
