"""add tcs factor snapshots

Revision ID: 49126c697e4d
Revises: 6440ad4dd6c7
Create Date: 2026-08-05 16:08:15.693156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49126c697e4d'
down_revision: Union[str, Sequence[str], None] = '6440ad4dd6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcs_factor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('current_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('delta_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['score_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcs_factor_snapshots_score_snapshot_id'), 'tcs_factor_snapshots', ['score_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tcs_factor_snapshots_score_snapshot_id'), table_name='tcs_factor_snapshots')
    op.drop_table('tcs_factor_snapshots')
    # ### end Alembic commands ###
