"""add financial observations

Revision ID: 6440ad4dd6c7
Revises: f2976136c966
Create Date: 2026-08-04 13:33:25.624659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6440ad4dd6c7'
down_revision: Union[str, Sequence[str], None] = 'f2976136c966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('period_type', sa.String(length=30), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_observations')
    # ### end Alembic commands ###
