"""add financial adjustments

Revision ID: 82ce0e4d50bd
Revises: 176e2ebb16b9
Create Date: 2026-08-06 14:44:10.868987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ce0e4d50bd'
down_revision: Union[str, Sequence[str], None] = '176e2ebb16b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_observation_id', sa.Integer(), nullable=False),
    sa.Column('source_raw_item_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_observation_id'], ['financial_observations.id'], ),
    sa.ForeignKeyConstraint(['source_raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_adjustments_financial_observation_id'), 'financial_adjustments', ['financial_observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_adjustments_financial_observation_id'), table_name='financial_adjustments')
    op.drop_table('financial_adjustments')
    # ### end Alembic commands ###
