"""add management guidance target rules

Revision ID: 82d66f2e1ab2
Revises: f4b5321dc34b
Create Date: 2026-08-07 13:54:36.339073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d66f2e1ab2'
down_revision: Union[str, Sequence[str], None] = 'f4b5321dc34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management_guidance', sa.Column('target_rule', sa.String(length=30), nullable=True))
    op.add_column('management_guidance', sa.Column('target_min', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('management_guidance', sa.Column('target_max', sa.Numeric(precision=20, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('management_guidance', 'target_max')
    op.drop_column('management_guidance', 'target_min')
    op.drop_column('management_guidance', 'target_rule')
    # ### end Alembic commands ###
