"""add thesis evidence

Revision ID: 8856cd2509f4
Revises: bd94a35febeb
Create Date: 2026-08-03 14:45:57.112961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8856cd2509f4'
down_revision: Union[str, Sequence[str], None] = 'bd94a35febeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_evidence')
    # ### end Alembic commands ###
