"""add score snapshots

Revision ID: a05cf645fee9
Revises: 0bb85d5f10e4
Create Date: 2026-08-03 14:11:34.925198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05cf645fee9'
down_revision: Union[str, Sequence[str], None] = '0bb85d5f10e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rgs_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dss_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tcs_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mrs_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('thesis_summary', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_snapshots')
    # ### end Alembic commands ###
