"""extend change records materiality

Revision ID: f2976136c966
Revises: 0072ec287e7b
Create Date: 2026-08-04 13:08:53.767907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2976136c966'
down_revision: Union[str, Sequence[str], None] = '0072ec287e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_records', sa.Column('magnitude_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('persistence_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('economic_importance_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('novelty_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('change_records', sa.Column('materiality_band', sa.String(length=30), nullable=True))
    op.add_column('change_records', sa.Column('materiality_model_version', sa.String(length=30), nullable=True))
    op.add_column('change_records', sa.Column('comparison_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_records', 'comparison_type')
    op.drop_column('change_records', 'materiality_model_version')
    op.drop_column('change_records', 'materiality_band')
    op.drop_column('change_records', 'novelty_score')
    op.drop_column('change_records', 'economic_importance_score')
    op.drop_column('change_records', 'persistence_score')
    op.drop_column('change_records', 'magnitude_score')
    # ### end Alembic commands ###
