"""add management delivery tables

Revision ID: f4b5321dc34b
Revises: 5a37e88f59ac
Create Date: 2026-08-07 13:30:33.371741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b5321dc34b'
down_revision: Union[str, Sequence[str], None] = '5a37e88f59ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_guidance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('guidance_type', sa.String(length=30), nullable=False),
    sa.Column('guidance_text', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('target_period', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_guidance_company_id'), 'management_guidance', ['company_id'], unique=False)
    op.create_table('management_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guidance_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_text', sa.Text(), nullable=True),
    sa.Column('outcome_period', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guidance_id'], ['management_guidance.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_outcomes_guidance_id'), 'management_outcomes', ['guidance_id'], unique=False)
    op.create_table('management_delivery_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guidance_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('delivery_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guidance_id'], ['management_guidance.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['management_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_delivery_assessments_guidance_id'), 'management_delivery_assessments', ['guidance_id'], unique=False)
    op.create_index(op.f('ix_management_delivery_assessments_outcome_id'), 'management_delivery_assessments', ['outcome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_management_delivery_assessments_outcome_id'), table_name='management_delivery_assessments')
    op.drop_index(op.f('ix_management_delivery_assessments_guidance_id'), table_name='management_delivery_assessments')
    op.drop_table('management_delivery_assessments')
    op.drop_index(op.f('ix_management_outcomes_guidance_id'), table_name='management_outcomes')
    op.drop_table('management_outcomes')
    op.drop_index(op.f('ix_management_guidance_company_id'), table_name='management_guidance')
    op.drop_table('management_guidance')
    # ### end Alembic commands ###
