import assert from "node:assert/strict";
import { getReviewJobs, readStoredReviewJobs, refreshReviewJob, reviewActivityLabel, reviewStatusErrors, setReviewJobs, startReviewActivityPolling, trackReviewJob } from "../src/fundamental-review-activity.ts";
import { normalizeFundamentalReviewJob, publishedFundamentalReviewResult } from "../src/fundamental-review-contract.ts";

const make = (status: string, extra = {}) => normalizeFundamentalReviewJob({ jobId: "test-job", symbol: "ADANIPORTS", companyName: "Adani Ports", status, updatedAt: "2026-10-06T09:00:00Z", ...extra }, { symbol: "ADANIPORTS" });
assert.deepEqual(readStoredReviewJobs({ getItem: () => "bad json" }), {});
assert.deepEqual(readStoredReviewJobs({ getItem: () => '[1,2]' }), {});
assert.deepEqual(readStoredReviewJobs({ getItem: () => JSON.stringify({ "../../bad": make("queued") }) }), {});
assert.equal(Object.keys(readStoredReviewJobs({ getItem: () => JSON.stringify({ ADANIPORTS: make("queued") }) })).length, 1);
assert.match(reviewActivityLabel("incomplete"), /finished.*no FCS/);
assert.match(reviewActivityLabel("failed"), /stopped/);
assert.equal(make("incomplete", { resultAvailable: true }).resultAvailable, false);
assert.equal(publishedFundamentalReviewResult({ ...make("incomplete"), scoreResult: { fcs_score: 60, score_publishable: true } }), null);
const successful = { ...make("ready", { completedFactors: 4 }), scoreResult: { fcs_score: 60, score_publishable: true, secret: "not public", lifecycle_ready: false } };
assert.deepEqual(publishedFundamentalReviewResult(successful), { fcs_score: 60, score_publishable: true, lifecycle_ready: false });
assert.equal(publishedFundamentalReviewResult({ ...successful, completedFactors: 3 }), null);
assert.equal(publishedFundamentalReviewResult({ ...successful, scoreResult: { fcs_score: NaN, score_publishable: true } }), null);

const storage = new Map<string, string>();
let interval: (() => void) | undefined;
let cleared = false;
(globalThis as any).window = { localStorage: { getItem: (key: string) => storage.get(key) || null, setItem: (key: string, value: string) => storage.set(key, value) }, setInterval: (fn: () => void) => { interval = fn; return 1; }, clearInterval: () => { cleared = true; }, addEventListener() {}, removeEventListener() {} };
(globalThis as any).document = { hidden: false, addEventListener() {}, removeEventListener() {} };
setReviewJobs({}); trackReviewJob(make("queued"));
assert.equal(storage.size, 1);
let calls = 0;
let finish: (() => void) | undefined;
globalThis.fetch = (async () => { calls++; await new Promise<void>((resolve) => { finish = resolve; }); return new Response(JSON.stringify({ job: make("incomplete", { updatedAt: "2026-10-06T09:02:00Z" }) }), { status: 200 }); });
const first = refreshReviewJob("ADANIPORTS"); const second = refreshReviewJob("ADANIPORTS");
assert.equal(first, second); assert.equal(calls, 1); finish!(); await first;
assert.equal(getReviewJobs().ADANIPORTS.status, "incomplete");
trackReviewJob(make("queued")); assert.equal(getReviewJobs().ADANIPORTS.status, "incomplete", "Older responses must not overwrite a finished job");
globalThis.fetch = (async () => { throw new Error("Network unavailable"); }) as typeof fetch;
await refreshReviewJob("ADANIPORTS");
assert.equal(getReviewJobs().ADANIPORTS.status, "incomplete"); assert.match(reviewStatusErrors.ADANIPORTS, /Network/);
globalThis.fetch = (async () => { calls++; return new Response(JSON.stringify({ job: getReviewJobs().ADANIPORTS }), { status: 200 }); });
const stop = startReviewActivityPolling(); await new Promise((resolve) => setTimeout(resolve, 0));
const afterRestore = calls; interval!(); await new Promise((resolve) => setTimeout(resolve, 0));
assert.equal(calls, afterRestore, "Completed reviews must not be polled continuously");
stop(); assert.equal(cleared, true);
setReviewJobs({ ADANIPORTS: make("validating_factors", { updatedAt: "2026-10-06T09:03:00Z", completedFactors: 2 }) });
const stopActive = startReviewActivityPolling(); await new Promise((resolve) => setTimeout(resolve, 0));
const beforeActiveTick = calls; interval!(); await new Promise((resolve) => setTimeout(resolve, 0));
assert.equal(calls, beforeActiveTick + 1, "Active requests must continue polling independently of the initiating page");
stopActive();
console.log("FCS shared activity: persistence, deduplication, terminal outcomes, safe result publication and polling verified.");
