import assert from 'node:assert/strict';
import {fcsPublicationSummaries,mergeFcsPublications} from '../src/fcs-publications.ts';
import {InMemoryFundamentalReviewStore,FirestoreFundamentalReviewStore} from '../src/fundamental-review-store.ts';
const record:any={jobId:'hcl-one',symbol:'HCLTECH',companyName:'HCL Technologies Limited',status:'ready',completedFactors:4,totalFactors:4,resultAvailable:true,informationCutoff:'2026-10-07',requestedAt:'2026-10-07T00:00:00Z',updatedAt:'2026-10-07T01:00:00Z',message:'Ready',evidenceRows:[],diagnostics:['PRIVATE_DIAGNOSTIC'],scoreResult:{score_publishable:true,fcs_score:72,lifecycle_ready:true,current_period:{label:'Q1 FY27',end_date:'2026-06-30'},checkpoints:[{},{},{}],lifecycle_assessment:{classification:'REBOUNDING',latestPeriodEnd:'2026-06-30',checkpoints:[{},{},{}]}},failureCode:null};
record.scoreResult.checkpoints=['2025-12-31','2026-03-31','2026-06-30'].map(periodEnd=>({periodEnd,completeFactors:4}));
const summary=fcsPublicationSummaries([record],'2026-10-07');assert.equal(summary.length,1);assert.equal(summary[0].lifecycleReady,true);
assert.ok(!JSON.stringify(summary).includes('PRIVATE_DIAGNOSTIC'));assert.ok(!JSON.stringify(summary).includes('hcl-one'));
assert.equal(fcsPublicationSummaries([{...record,status:'incomplete'}],'2026-10-07').length,0);
assert.equal(fcsPublicationSummaries([{...record,informationCutoff:'2026-10-08'}],'2026-10-07').length,0);
assert.equal(fcsPublicationSummaries([{...record,scoreResult:{...record.scoreResult,score_publishable:false}}],'2026-10-07').length,0);
const mismatched=fcsPublicationSummaries([{...record,scoreResult:{...record.scoreResult,lifecycle_assessment:{...record.scoreResult.lifecycle_assessment,latestPeriodEnd:'2026-03-31'}}}],'2026-10-07');assert.equal(mismatched[0].lifecycleReady,false);
assert.equal(fcsPublicationSummaries([{...record,scoreResult:{...record.scoreResult,current_period:null,checkpoints:[]}}],'2026-10-07').length,0,'Legacy worker reports cannot replace validated library snapshots');
const base=[{symbol:'HCLTECH',fcsAsOf:'2026-08-26',fcsScore:65,fcsPeriod:'Q3 FY26',lifecycle:null,lifecycleReady:false,checkpoints:1}];
const old=structuredClone(base);const merged=mergeFcsPublications(base,summary);assert.deepEqual(base,old);assert.equal(merged[0].fcsScore,72);assert.equal(merged[0].lifecycleReady,true);assert.equal(merged[0].checkpoints,3);
assert.equal(mergeFcsPublications(base,[{...summary[0],symbol:'UNKNOWN'}]).length,1);
const admitted=mergeFcsPublications(base,[{...summary[0],symbol:'UNKNOWN'}],publication=>({symbol:publication.symbol,fcsAsOf:publication.informationCutoff,fcsScore:publication.fcsScore,fcsPeriod:publication.fcsPeriod,lifecycle:publication.lifecycle,lifecycleReady:publication.lifecycleReady,checkpoints:publication.checkpoints}));
assert.equal(admitted.length,2);assert.equal(admitted[1].symbol,'UNKNOWN');assert.deepEqual(base,old);
assert.equal(mergeFcsPublications(base,[{...summary[0],symbol:'UNKNOWN',fcsScore:NaN}],()=>{throw Error('Invalid score must never be admitted')}).length,1);
assert.deepEqual(mergeFcsPublications(base,[{...summary[0],informationCutoff:'2026-01-01'}]),base);
const memory=new InMemoryFundamentalReviewStore();await memory.save(record);assert.equal((await memory.listLatest()).length,1);
await memory.save({...record,jobId:'hcl-two',updatedAt:'2026-10-07T02:00:00Z'});assert.equal((await memory.listLatest()).length,1);assert.equal((await memory.readJob('hcl-one'))!.jobId,'hcl-one');
let requests=0;
const store=new FirestoreFundamentalReviewStore({projectId:'test',tokenProvider:async()=>'test-token',fetch:(async (url:any)=>{requests++;assert.ok(String(url).endsWith('fundamental_review_jobs_v1_latest?pageSize=200'));return new Response(JSON.stringify({documents:[{fields:{payload:{stringValue:JSON.stringify(record)}}}]}));}) as typeof fetch});
assert.equal((await store.listLatest())[0].symbol,'HCLTECH');assert.equal(requests,1);
const paged=new FirestoreFundamentalReviewStore({projectId:'test',tokenProvider:async()=>'test-token',fetch:(async()=>new Response(JSON.stringify({nextPageToken:'more'}))) as typeof fetch});
await assert.rejects(()=>paged.listLatest(),/pagination required/);
console.log('Publication list: read-only capped storage, ready-only public fields, cutoff checks, dated history, immutable library merge and frozen baseline preservation passed. No model calls or production writes.');
